import Head from 'next/head'

import { getPostsData } from '../lib/post'; // import文を修正
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Layout ,{siteTitle} from '../components/Layout';
import utilsStyle from '../styles/utils.module.css';
// import { siteTitle } from '@/components/Layout';

//SSGの場合(ビルド)
//外部から一度だけデータを持ってくる
export async function getStaticProps(){
  const allPostData = getPostsData();//id,title,date,thumbnail
  console.log(allPostData);
  return{
    props:{
      allPostData,
    }
  }
}

//SSRの場合(リクエスト)
// export async function getServerSideProps(context){
//   return 
//   props:{
//     //コンポーネントにわたすためのprops
//   }
// }

export default function Home({allPostData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        <Link href="./posts/firstPost">最初の投稿へ</Link>
          <section className={`${utilsStyle.headingMd} ${utilsStyle.padding1px}`}>
            <p>私はNext.jsエンジニアです/好きなフレームワークはNext.jsです!</p>
          </section>
        <Layout home>
          <Head>
            <title>{siteTitle}</title>
          </Head>
          <section className={utilsStyle.headingMd}>
            <h2>エンジニアのブログです</h2>
        
            <div className={styles.grid}>
              {allPostData.map(({id,title,date,thumbnail},num)=>(
                  <article key={id}>
                  <Link href={`/posts/${id}`}>
                    <img src={`${thumbnail}`}
                      className={styles.thumbnailImage}
                    />
                  </Link>
                  <Link href={`/posts/${id}`}  className={utilsStyle.boldText}>
                  {title}
                  </Link><br/>
                  <small className={utilsStyle.lightText}>{date}</small>
                </article>
              ))}

            </div>
          </section>
        </Layout>
    </>
  )
}
